# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-GreaterVersion
version:      0.003
version_from: lib/Test/GreaterVersion.pm
installdirs:  site
requires:
    CPAN:                          0
    File::Spec:                    0
    Test::Builder:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
