--- #YAML:1.0
name:                Test-GreaterVersion
version:             0.009
abstract:            Test if you incremented VERSION
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    CPAN:                          0
    CPAN::Version:                 0
    Cwd:                           0
    File::Spec:                    0
    Test::Builder:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Gregor Goldbach <glauschwuffel@nomaden.org>
